name: flutter_dash_border_animated
description: "A package help you make the dash border animated for widget, Container, Sizedbox,..."
version: 0.0.5

homepage: https://github.com/K0Jack/flutter_dash_border_animated.git

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: