name: flutter_dash_border_animated
description: "Provides a little package rendering library for all application development by flutter team"
version: 0.0.2
authors: ["Linh Nguyen (KoJack Nguyen)<linhhn190998@gmail.com>"]

homepage: https://github.com/K0Jack/flutter_dash_border_animated.git

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: